### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Polyfill\Mbstring\iconv() in /cygdrive/d/projects/agfin/vendor/symfony/polyfill-mbstring/Mbstring.php:114

### ISSUE THREAD

**Issue by josefsabl** [Comcast/php-legal-licenses#8]
Hello, I am getting this error. I installed this package as a local dev package in the project. May that be the problem?

PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Polyfill\Mbstring\iconv() in /cygdrive/d/projects/agfin/vendor/symfony/polyfill-mbstring/Mbstring.php:114

Stack trace:
#0 /cygdrive/d/projects/agfin/vendor/symfony/polyfill-mbstring/bootstrap.php(19): Symfony\Polyfill\Mbstring\Mbstring::mb_convert_encoding('Composer Lock f...', 'UTF-8', 'ASCII')
#1 /cygdrive/d/projects/agfin/vendor/symfony/console/Application.php(1125): mb_convert_encoding('Composer Lock f...', 'utf8', 'ASCII')
#2 /cygdrive/d/projects/agfin/vendor/symfony/console/Application.php(780): Symfony\Component\Console\Application->splitStringByWidth('Composer Lock f...', 199)
#3 /cygdrive/d/projects/agfin/vendor/symfony/console/Application.php(750): Symfony\Component\Console\Application->doRenderException(Object(RuntimeException), Object(Symfony\Component\Console\Output\StreamOutput))
#4 /cygdrive/d/projects/agfin/vendor/symfony/console/Application.php(128): Symfony\Component\Console\Application->renderException(Object(RuntimeException), Object(Symfo in /cygdrive/d/projects/agfin/vendor/symfony/polyfill-mbstring/Mbstring.php on line 114

**Comment by josefsabl** [comment]
Looks like it is some composer problem. Disregard this.
